//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FInalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ammenities
    {
        public int ammenitiesId { get; set; }
        public string ammenitiesName { get; set; }
        public string ammenitiesRate { get; set; }
    }
}
