//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FInalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Billing
    {
        public Billing()
        {
            this.Car_carId = 11;
            this.Customer_customerId = 100;
            this.Hub_hubId = 500;
        }
    
        public int billingId { get; set; }
        public int CarCategories_categoryId { get; set; }
        public Nullable<int> Car_carId { get; set; }
        public int Booking_bookingId { get; set; }
        public int Customer_customerId { get; set; }
        public string billingName { get; set; }
        public string fuelStatus { get; set; }
        public string startDate { get; set; }
        public string endDate { get; set; }
        public string userMailid { get; set; }
        public string customerMobNo { get; set; }
        public int Hub_hubId { get; set; }
        public Nullable<int> Amount { get; set; }
    
        public virtual CarCategories CarCategory { get; set; }
        public virtual Car Car { get; set; }
        public virtual Booking Booking { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Hub Hub { get; set; }
    }
}
