//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FInalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public Booking()
        {
            this.Hub_hubId = 500;
            this.City_cityId = 700;
            this.State_stateId = 1000;
            this.Customer_customerId = 100;
            this.Billings = new HashSet<Billing>();
        }
    
        public int bookingId { get; set; }
        public string bookingdateAndTime { get; set; }
        public string customerFirstName { get; set; }
        public string customerLastName { get; set; }
        public long customerMobileNo { get; set; }
        public string usermailId { get; set; }
        public string customerDLNo { get; set; }
        public string dropdateAndTime { get; set; }
        public int Hub_hubId { get; set; }
        public int City_cityId { get; set; }
        public int State_stateId { get; set; }
        public int CarCategories_categoryId { get; set; }
        public int Customer_customerId { get; set; }
        public string Status { get; set; }
        public Nullable<int> Amount { get; set; }
    
        public virtual Hub Hub { get; set; }
        public virtual City City { get; set; }
        public virtual State State { get; set; }
        public virtual CarCategories CarCategory { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual ICollection<Billing> Billings { get; set; }
    }
}
