//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FInalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public Car()
        {
            this.carId = 11;
            this.Billings = new HashSet<Billing>();
        }
    
        public int carId { get; set; }
        public string carName { get; set; }
        public string carNoPlate { get; set; }
        public int capacity { get; set; }
        public string fuelType { get; set; }
        public int availability { get; set; }
        public int CarCategories_categoryId { get; set; }
        public int Hub_hubId { get; set; }
    
        public virtual CarCategories CarCategory { get; set; }
        public virtual Hub Hub { get; set; }
        public virtual ICollection<Billing> Billings { get; set; }
    }
}
