//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FInalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarCategories
    {
        public CarCategories()
        {
            this.Cars = new HashSet<Car>();
            this.Bookings = new HashSet<Booking>();
            this.Billings = new HashSet<Billing>();
        }
    
        public int categoryId { get; set; }
        public string categoryName { get; set; }
        public string imagePath { get; set; }
        public decimal dailyRates { get; set; }
        public decimal monthlyRates { get; set; }
        public decimal weeklyRates { get; set; }
    
        public virtual ICollection<Car> Cars { get; set; }
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual ICollection<Billing> Billings { get; set; }
    }
}
