//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FInalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.cityId = 700;
            this.State_stateId = 1000;
            this.Hubs = new HashSet<Hub>();
            this.Bookings = new HashSet<Booking>();
        }
    
        public int cityId { get; set; }
        public string cityName { get; set; }
        public int State_stateId { get; set; }
        public string airportcode { get; set; }
    
        public virtual State State { get; set; }
        public virtual ICollection<Hub> Hubs { get; set; }
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}
