//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FInalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.customerId = 100;
            this.Bookings = new HashSet<Booking>();
            this.Billings = new HashSet<Billing>();
        }
    
        public int customerId { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string address { get; set; }
        public string emailId { get; set; }
        public string city { get; set; }
        public long cellNo { get; set; }
        public string creditcardType { get; set; }
        public long creditcard_Number { get; set; }
        public long drivingLiscen_Number { get; set; }
        public string validThrough { get; set; }
        public long passport_Number { get; set; }
        public string passport_valid { get; set; }
        public string password { get; set; }
    
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual ICollection<Billing> Billings { get; set; }
    }
}
