//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FInalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Hub_hubId = 500;
        }
    
        public int empId { get; set; }
        public string empName { get; set; }
        public long empMobNo { get; set; }
        public string empMailId { get; set; }
        public string empAddress { get; set; }
        public int empSalary { get; set; }
        public string empPassword { get; set; }
        public int Hub_hubId { get; set; }
    
        public virtual Hub Hub { get; set; }
    }
}
