//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FInalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hub
    {
        public Hub()
        {
            this.hubId = 500;
            this.City_cityId = 700;
            this.Cars = new HashSet<Car>();
            this.Employees = new HashSet<Employee>();
            this.Bookings = new HashSet<Booking>();
            this.Billings = new HashSet<Billing>();
        }
    
        public int hubId { get; set; }
        public string hubName { get; set; }
        public long contactNumber { get; set; }
        public string address { get; set; }
        public int stateId { get; set; }
        public int City_cityId { get; set; }
    
        public virtual ICollection<Car> Cars { get; set; }
        public virtual City City { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual ICollection<Billing> Billings { get; set; }
    }
}
