//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FInalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        public State()
        {
            this.stateId = 1000;
            this.Cities = new HashSet<City>();
            this.Bookings = new HashSet<Booking>();
        }
    
        public int stateId { get; set; }
        public string stateName { get; set; }
    
        public virtual ICollection<City> Cities { get; set; }
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}
